import "server-only";

import { db } from "./database";
import type { Screen } from "./erp-modules";

type DataRow = Record<string, string | number>;
export type ScreenData = { columns: { key: string; label: string }[]; rows: DataRow[]; empty: string };
const money = (cents: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(cents / 100);
const date = (value: string) => new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(new Date(value));
const status: Record<string, string> = { ACTIVE: "Ativo", PAID: "Pago", PICKING: "Em separação", SHIPPED: "Enviado", PENDING: "Pendente", OPEN: "Em aberto", OVERDUE: "Atrasado", CONNECTED: "Conectado" };

export function dashboardSummary(storeId: string) {
  const revenue = db.prepare("SELECT COALESCE(SUM(total_cents), 0) AS total, COUNT(*) AS count FROM orders WHERE store_id = ? AND status <> 'CANCELLED'").get(storeId) as unknown as { total: number; count: number };
  const stock = db.prepare("SELECT COALESCE(SUM(on_hand), 0) AS units, SUM(CASE WHEN on_hand <= minimum THEN 1 ELSE 0 END) AS low FROM products WHERE store_id = ? AND status = 'ACTIVE'").get(storeId) as unknown as { units: number; low: number };
  const customers = db.prepare("SELECT COUNT(*) AS count FROM customers WHERE store_id = ?").get(storeId) as unknown as { count: number };
  const notifications = db.prepare("SELECT COUNT(*) AS count FROM notifications WHERE store_id = ? AND read_at IS NULL").get(storeId) as unknown as { count: number };
  const recentOrders = db.prepare("SELECT id, customer_name AS customer, total_cents AS total, status, created_at AS createdAt FROM orders WHERE store_id = ? ORDER BY created_at DESC LIMIT 5").all(storeId) as unknown as { id: string; customer: string; total: number; status: string; createdAt: string }[];
  const lowStock = db.prepare("SELECT id, sku, name, on_hand AS onHand, minimum, location FROM products WHERE store_id = ? AND status = 'ACTIVE' ORDER BY (on_hand <= minimum) DESC, on_hand ASC LIMIT 5").all(storeId) as unknown as { id: string; sku: string; name: string; onHand: number; minimum: number; location: string }[];
  return { revenue: money(revenue.total), orders: revenue.count, units: stock.units, low: stock.low, customers: customers.count, notifications: notifications.count, recentOrders: recentOrders.map((order) => ({ ...order, total: money(order.total), status: status[order.status] ?? order.status })), lowStock };
}

export function screenData(screen: Screen, storeId: string): ScreenData {
  if (screen === "produtos" || screen === "estoque") { const rows = db.prepare("SELECT id, sku, name, on_hand, minimum, location, price_cents, status FROM products WHERE store_id = ? AND status = 'ACTIVE' ORDER BY name").all(storeId) as unknown as { id: string; sku: string; name: string; on_hand: number; minimum: number; location: string; price_cents: number; status: string }[]; return { columns: screen === "produtos" ? [{ key: "sku", label: "SKU" }, { key: "name", label: "Produto" }, { key: "price", label: "Preço" }, { key: "stock", label: "Estoque" }, { key: "state", label: "Situação" }] : [{ key: "location", label: "Localização" }, { key: "sku", label: "SKU" }, { key: "name", label: "Produto" }, { key: "stock", label: "Saldo" }, { key: "minimum", label: "Mínimo" }], rows: rows.map((row) => ({ id: row.id, sku: row.sku, name: row.name, price: money(row.price_cents), stock: row.on_hand, minimum: row.minimum, location: row.location, state: row.on_hand <= row.minimum ? "Estoque baixo" : status[row.status] ?? row.status })), empty: "Nenhum produto cadastrado." }; }
  if (screen === "pedidos") { const rows = db.prepare("SELECT id, customer_name, total_cents, status, created_at FROM orders WHERE store_id = ? ORDER BY created_at DESC").all(storeId) as unknown as { id: string; customer_name: string; total_cents: number; status: string; created_at: string }[]; return { columns: [{ key: "id", label: "Pedido" }, { key: "customer", label: "Cliente" }, { key: "total", label: "Total" }, { key: "state", label: "Situação" }, { key: "created", label: "Data" }], rows: rows.map((row) => ({ id: row.id, customer: row.customer_name, total: money(row.total_cents), state: status[row.status] ?? row.status, rawStatus: row.status, created: date(row.created_at) })), empty: "Nenhum pedido registrado." }; }
  if (screen === "clientes") { const rows = db.prepare("SELECT name, email, orders_count, total_spent_cents, status FROM customers WHERE store_id = ? ORDER BY total_spent_cents DESC").all(storeId) as unknown as { name: string; email: string; orders_count: number; total_spent_cents: number; status: string }[]; return { columns: [{ key: "name", label: "Cliente" }, { key: "email", label: "E-mail" }, { key: "orders", label: "Pedidos" }, { key: "spent", label: "Valor total" }, { key: "state", label: "Situação" }], rows: rows.map((row) => ({ name: row.name, email: row.email, orders: row.orders_count, spent: money(row.total_spent_cents), state: status[row.status] ?? row.status })), empty: "Nenhum cliente cadastrado." }; }
  if (screen === "financeiro") { const rows = db.prepare("SELECT description, type, amount_cents, due_at, status FROM financial_entries WHERE store_id = ? ORDER BY due_at").all(storeId) as unknown as { description: string; type: string; amount_cents: number; due_at: string; status: string }[]; return { columns: [{ key: "description", label: "Descrição" }, { key: "type", label: "Tipo" }, { key: "amount", label: "Valor" }, { key: "due", label: "Vencimento" }, { key: "state", label: "Situação" }], rows: rows.map((row) => ({ description: row.description, type: row.type === "PAYABLE" ? "A pagar" : "A receber", amount: money(row.amount_cents), due: date(row.due_at), state: status[row.status] ?? row.status })), empty: "Nenhum lançamento financeiro." }; }
  if (screen === "notificacoes") { const rows = db.prepare("SELECT title, message, kind, read_at, created_at FROM notifications WHERE store_id = ? ORDER BY created_at DESC").all(storeId) as unknown as { title: string; message: string; kind: string; read_at: string | null; created_at: string }[]; return { columns: [{ key: "title", label: "Notificação" }, { key: "message", label: "Detalhe" }, { key: "kind", label: "Categoria" }, { key: "state", label: "Situação" }, { key: "created", label: "Data" }], rows: rows.map((row) => ({ title: row.title, message: row.message, kind: row.kind, state: row.read_at ? "Lida" : "Não lida", created: date(row.created_at) })), empty: "Nenhuma notificação." }; }
  if (screen === "fornecedores" || screen === "compras") { const rows = db.prepare("SELECT name, contact, lead_time_days, status FROM suppliers WHERE store_id = ? ORDER BY name").all(storeId) as unknown as { name: string; contact: string; lead_time_days: number; status: string }[]; return { columns: [{ key: "name", label: "Fornecedor" }, { key: "contact", label: "Contato" }, { key: "lead", label: "Prazo médio" }, { key: "state", label: "Situação" }], rows: rows.map((row) => ({ name: row.name, contact: row.contact, lead: `${row.lead_time_days} dias`, state: status[row.status] ?? row.status })), empty: "Nenhum fornecedor cadastrado." }; }
  if (screen === "cupons") { const rows = db.prepare("SELECT code, discount_percent, uses_count, status FROM coupons WHERE store_id = ? ORDER BY code").all(storeId) as unknown as { code: string; discount_percent: number; uses_count: number; status: string }[]; return { columns: [{ key: "code", label: "Cupom" }, { key: "discount", label: "Desconto" }, { key: "uses", label: "Usos" }, { key: "state", label: "Situação" }], rows: rows.map((row) => ({ code: row.code, discount: `${row.discount_percent}%`, uses: row.uses_count, state: status[row.status] ?? row.status })), empty: "Nenhum cupom criado." }; }
  if (screen === "integracoes") { const rows = db.prepare("SELECT name, category, status FROM integrations WHERE store_id = ? ORDER BY name").all(storeId) as unknown as { name: string; category: string; status: string }[]; return { columns: [{ key: "name", label: "Integração" }, { key: "category", label: "Categoria" }, { key: "state", label: "Situação" }], rows: rows.map((row) => ({ name: row.name, category: row.category, state: status[row.status] ?? row.status })), empty: "Nenhuma integração configurada." }; }
  if (screen === "equipe") { const rows = db.prepare("SELECT name, email, role, status FROM users WHERE store_id = ? ORDER BY name").all(storeId) as unknown as { name: string; email: string; role: string; status: string }[]; return { columns: [{ key: "name", label: "Pessoa" }, { key: "email", label: "E-mail" }, { key: "role", label: "Papel" }, { key: "state", label: "Situação" }], rows: rows.map((row) => ({ name: row.name, email: row.email, role: row.role, state: status[row.status] ?? row.status })), empty: "Nenhum membro na equipe." }; }
  if (screen === "seguranca") { const rows = db.prepare("SELECT action, entity, entity_id, created_at FROM audit_events WHERE store_id = ? ORDER BY created_at DESC LIMIT 100").all(storeId) as unknown as { action: string; entity: string; entity_id: string; created_at: string }[]; return { columns: [{ key: "action", label: "Ação" }, { key: "entity", label: "Entidade" }, { key: "entityId", label: "Identificador" }, { key: "created", label: "Data" }], rows: rows.map((row) => ({ action: row.action, entity: row.entity, entityId: row.entity_id ?? "—", created: new Date(row.created_at).toLocaleString("pt-BR") })), empty: "Nenhum evento de auditoria." }; }
  if (screen === "loja") { const row = db.prepare("SELECT name, slug, status, created_at FROM stores WHERE id = ?").get(storeId) as unknown as { name: string; slug: string; status: string; created_at: string }; return { columns: [{ key: "name", label: "Loja" }, { key: "url", label: "Loja pública" }, { key: "state", label: "Situação" }, { key: "created", label: "Criada em" }], rows: [{ name: row.name, url: `/loja/${row.slug}`, state: status[row.status] ?? row.status, created: date(row.created_at) }], empty: "Loja não encontrada." }; }
  if (screen === "entregas") { const rows = db.prepare("SELECT s.id, o.customer_name, s.carrier, s.tracking_code, s.status FROM shipments s JOIN orders o ON o.id = s.order_id WHERE s.store_id = ?").all(storeId) as unknown as { id: string; customer_name: string; carrier: string; tracking_code: string; status: string }[]; return { columns: [{ key: "id", label: "Entrega" }, { key: "customer", label: "Cliente" }, { key: "carrier", label: "Transportadora" }, { key: "tracking", label: "Rastreio" }, { key: "state", label: "Situação" }], rows: rows.map((row) => ({ id: row.id, customer: row.customer_name, carrier: row.carrier, tracking: row.tracking_code, state: row.status })), empty: "Nenhuma entrega em andamento." }; }
  if (screen === "metricas") { const summary = dashboardSummary(storeId); return { columns: [{ key: "indicator", label: "Indicador" }, { key: "value", label: "Valor atual" }, { key: "context", label: "Contexto" }], rows: [{ indicator: "Receita", value: summary.revenue, context: "Pedidos não cancelados" }, { indicator: "Pedidos", value: summary.orders, context: "Total do período" }, { indicator: "Clientes", value: summary.customers, context: "Base ativa" }, { indicator: "Produtos críticos", value: summary.low, context: "Abaixo do mínimo" }], empty: "Sem métricas disponíveis." }; }
  return { columns: [{ key: "report", label: "Relatório" }, { key: "format", label: "Formato" }, { key: "scope", label: "Abrangência" }], rows: [{ report: "Vendas por pedido", format: "CSV", scope: "Pedidos e clientes" }, { report: "Posição de estoque", format: "CSV", scope: "Produtos e localizações" }, { report: "Fluxo financeiro", format: "CSV", scope: "Contas a pagar e receber" }], empty: "Nenhum relatório disponível." };
}
