import "server-only";

import { randomUUID } from "node:crypto";
import { db, nowIso, transaction } from "./database";

export type Product = { id: string; sku: string; name: string; priceCents: number; costCents: number; onHand: number; minimum: number; location: string; status: string; lowStock: boolean };
export type Order = { id: string; customer: string; totalCents: number; status: string; createdAt: string };
type ProductRow = { id: string; sku: string; name: string; price_cents: number; cost_cents: number; on_hand: number; minimum: number; location: string; status: string };
type OrderRow = { id: string; customer_name: string; total_cents: number; status: string; created_at: string };

function mapProduct(row: ProductRow): Product { return { id: row.id, sku: row.sku, name: row.name, priceCents: row.price_cents, costCents: row.cost_cents, onHand: row.on_hand, minimum: row.minimum, location: row.location, status: row.status, lowStock: row.on_hand <= row.minimum }; }
export function listProducts(storeId: string) { return (db.prepare("SELECT id, sku, name, price_cents, cost_cents, on_hand, minimum, location, status FROM products WHERE store_id = ? AND status = 'ACTIVE' ORDER BY name").all(storeId) as unknown as ProductRow[]).map(mapProduct); }
export function createProduct(storeId: string, userId: string, input: { sku: string; name: string; priceCents: number; costCents: number; minimum: number; location: string }) { if (!Number.isInteger(input.priceCents) || input.priceCents < 0 || !Number.isInteger(input.costCents) || input.costCents < 0) throw new Error("Preço e custo devem ser valores positivos."); if (!Number.isInteger(input.minimum) || input.minimum < 0) throw new Error("Estoque mínimo inválido."); return transaction(() => { const id = randomUUID(), createdAt = nowIso(); db.prepare("INSERT INTO products (id, store_id, sku, name, price_cents, cost_cents, minimum, location, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)").run(id, storeId, input.sku, input.name, input.priceCents, input.costCents, input.minimum, input.location, createdAt); db.prepare("INSERT INTO audit_events (id, store_id, user_id, action, entity, entity_id, created_at) VALUES (?, ?, ?, 'CREATE', 'PRODUCT', ?, ?)").run(randomUUID(), storeId, userId, id, createdAt); const row = db.prepare("SELECT * FROM products WHERE id = ? AND store_id = ?").get(id, storeId) as unknown as ProductRow; return mapProduct(row); }); }
export function listOrders(storeId: string) { return (db.prepare("SELECT id, customer_name, total_cents, status, created_at FROM orders WHERE store_id = ? ORDER BY created_at DESC LIMIT 100").all(storeId) as unknown as OrderRow[]).map((row) => ({ id: row.id, customer: row.customer_name, totalCents: row.total_cents, status: row.status, createdAt: row.created_at })); }
export function moveStock(storeId: string, userId: string, input: { productId: string; type: "IN" | "OUT" | "TRANSFER" | "ADJUSTMENT"; quantity: number; location: string; reason: string }) { if (!(["IN", "OUT", "TRANSFER", "ADJUSTMENT"] as const).includes(input.type)) throw new Error("Tipo de movimento inválido."); if (!Number.isInteger(input.quantity) || input.quantity <= 0) throw new Error("A quantidade deve ser um inteiro positivo."); if (input.reason.trim().length < 3) throw new Error("Informe o motivo do movimento."); return transaction(() => { const row = db.prepare("SELECT * FROM products WHERE id = ? AND store_id = ? AND status = 'ACTIVE'").get(input.productId, storeId) as unknown as ProductRow | undefined; if (!row) throw new Error("Produto não encontrado."); const direction = input.type === "OUT" ? -1 : input.type === "TRANSFER" ? 0 : 1, resulting = row.on_hand + direction * input.quantity; if (resulting < 0) throw new Error("Movimento bloqueado: estoque insuficiente."); if (input.type !== "TRANSFER") db.prepare("UPDATE products SET on_hand = ?, location = ? WHERE id = ? AND store_id = ?").run(resulting, input.location, input.productId, storeId); else db.prepare("UPDATE products SET location = ? WHERE id = ? AND store_id = ?").run(input.location, input.productId, storeId); const id = randomUUID(), createdAt = nowIso(); db.prepare("INSERT INTO stock_movements (id, store_id, product_id, type, quantity, location, reason, created_by, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)").run(id, storeId, input.productId, input.type, input.quantity, input.location, input.reason.trim(), userId, createdAt); db.prepare("INSERT INTO audit_events (id, store_id, user_id, action, entity, entity_id, metadata, created_at) VALUES (?, ?, ?, 'STOCK_MOVE', 'PRODUCT', ?, ?, ?)").run(randomUUID(), storeId, userId, input.productId, JSON.stringify({ type: input.type, quantity: input.quantity, resulting }), createdAt); return { movement: { id, ...input, createdAt }, product: { ...mapProduct(row), onHand: resulting, location: input.location, lowStock: resulting <= row.minimum } }; }); }
export function recentMovements(storeId: string) { return db.prepare("SELECT m.id, m.type, m.quantity, m.location, m.reason, m.created_at AS createdAt, p.name AS product FROM stock_movements m JOIN products p ON p.id = m.product_id WHERE m.store_id = ? ORDER BY m.created_at DESC LIMIT 30").all(storeId); }
