"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import type { Role } from "@/lib/auth";
import type { Screen } from "@/lib/erp-modules";
import styles from "./page.module.css";

type Field = { name: string; label: string; type?: string; placeholder?: string; min?: number; max?: number; step?: string; options?: [string, string][] };
type Config = { button: string; title: string; description: string; fields: Field[] };
const configs: Partial<Record<Screen, Config>> = {
  pedidos: { button: "+ Novo pedido", title: "Registrar pedido", description: "Crie um pedido que entrará no fluxo operacional.", fields: [{ name: "customer", label: "Cliente", placeholder: "Nome do cliente" }, { name: "total", label: "Valor total", type: "number", min: 0, step: "0.01" }] },
  clientes: { button: "+ Novo cliente", title: "Cadastrar cliente", description: "Inclua um contato na base da sua loja.", fields: [{ name: "name", label: "Nome completo" }, { name: "email", label: "E-mail", type: "email" }] },
  financeiro: { button: "+ Novo lançamento", title: "Novo lançamento", description: "Registre uma conta a pagar ou receber.", fields: [{ name: "description", label: "Descrição" }, { name: "type", label: "Tipo", options: [["RECEIVABLE", "A receber"], ["PAYABLE", "A pagar"]] }, { name: "amount", label: "Valor", type: "number", min: 0, step: "0.01" }, { name: "dueAt", label: "Vencimento", type: "date" }] },
  fornecedores: { button: "+ Novo fornecedor", title: "Cadastrar fornecedor", description: "Inclua contato e prazo médio de entrega.", fields: [{ name: "name", label: "Fornecedor" }, { name: "contact", label: "Contato" }, { name: "leadTime", label: "Prazo médio (dias)", type: "number", min: 0, step: "1" }] },
  compras: { button: "+ Nova fonte de compra", title: "Cadastrar fornecedor", description: "Cadastre uma fonte para futuras compras e reposições.", fields: [{ name: "name", label: "Fornecedor" }, { name: "contact", label: "Contato" }, { name: "leadTime", label: "Prazo médio (dias)", type: "number", min: 0, step: "1" }] },
  cupons: { button: "+ Novo cupom", title: "Criar cupom", description: "Defina um código e percentual de desconto.", fields: [{ name: "code", label: "Código", placeholder: "CLIENTE10" }, { name: "discount", label: "Desconto (%)", type: "number", min: 1, max: 100, step: "1" }] },
  entregas: { button: "+ Nova entrega", title: "Cadastrar entrega", description: "Vincule o rastreamento a um pedido existente.", fields: [{ name: "orderId", label: "Código do pedido" }, { name: "carrier", label: "Transportadora" }, { name: "tracking", label: "Código de rastreio" }] },
  integracoes: { button: "+ Nova integração", title: "Solicitar integração", description: "Registre uma conexão para configuração técnica.", fields: [{ name: "name", label: "Nome da integração" }, { name: "category", label: "Categoria", options: [["PAYMENT", "Pagamento"], ["SHIPPING", "Logística"], ["MARKETPLACE", "Marketplace"], ["OTHER", "Outra"]] }] },
  loja: { button: "Editar loja", title: "Alterar nome da loja", description: "A mudança será registrada na auditoria.", fields: [{ name: "name", label: "Novo nome da loja" }] },
  equipe: { button: "+ Novo usuário", title: "Criar acesso", description: "O novo usuário receberá um papel limitado pela sua permissão.", fields: [{ name: "name", label: "Nome completo" }, { name: "email", label: "E-mail", type: "email" }, { name: "password", label: "Senha temporária", type: "password" }] },
};
function csrf() { return document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("vendio_csrf="))?.slice("vendio_csrf=".length) ?? ""; }

export default function ModuleAction({ screen, products, role }: { screen: Screen; products: { id: string; name: string }[]; role: Role }) {
  const router = useRouter();
  const [open, setOpen] = useState(false), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const config = screen === "equipe" && !["ADMIN", "DEVELOPER", "OWNER"].includes(role) ? undefined : configs[screen], special = screen === "produtos" || screen === "estoque";
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const body = Object.fromEntries(new FormData(event.currentTarget)); const endpoint = screen === "produtos" ? "/api/erp/products" : screen === "estoque" ? "/api/erp/inventory/movements" : screen === "equipe" ? "/api/erp/team" : `/api/erp/actions/${screen}`; const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json", "x-csrf-token": csrf() }, body: JSON.stringify(body) }); const result = await response.json(); setBusy(false); if (!response.ok) { setMessage(result.message ?? "Não foi possível salvar."); return; } setMessage(result.message ?? "Operação concluída."); router.refresh(); setTimeout(() => setOpen(false), 700); }
  async function downloadReport(report: "sales" | "stock" | "finance") { const response = await fetch(`/api/reports/${report}.csv`, { method: "POST", headers: { "x-csrf-token": csrf() } }); if (!response.ok) { alert("Não foi possível exportar o relatório."); return; } const url = URL.createObjectURL(await response.blob()), link = document.createElement("a"); link.href = url; link.download = `vendio-${report}.csv`; link.click(); URL.revokeObjectURL(url); }
  async function contextualAction() { if (screen === "notificacoes") { const response = await fetch("/api/erp/notifications/read-all", { method: "POST", headers: { "x-csrf-token": csrf() } }); if (response.ok) router.refresh(); return; } document.getElementById("module-data")?.scrollIntoView({ behavior: "smooth" }); }
  const buttonLabel = special ? (screen === "produtos" ? "+ Novo produto" : "+ Movimentar estoque") : config?.button;
  if (!buttonLabel && screen === "relatorios") return <div style={{ display: "flex", flexWrap: "wrap", justifyContent: "end", gap: 6 }}><button className={styles.primaryAction} onClick={() => downloadReport("sales")}>CSV vendas</button><button className={styles.primaryAction} onClick={() => downloadReport("stock")}>CSV estoque</button><button className={styles.primaryAction} onClick={() => downloadReport("finance")}>CSV financeiro</button></div>;
  if (!buttonLabel) return <button className={styles.primaryAction} onClick={contextualAction}>{screen === "notificacoes" ? "Marcar tudo como lido" : "Ver dados"}</button>;
  let fields: React.ReactNode;
  if (screen === "produtos") fields = <><label>SKU<input name="sku" required pattern="[A-Z0-9_-]{3,40}" placeholder="CAM-ESS-002" /></label><label>Nome<input name="name" required minLength={3} /></label><div className={styles.formGrid}><label>Preço<input name="price" type="number" min="0" step="0.01" required /></label><label>Custo<input name="cost" type="number" min="0" step="0.01" required /></label></div><div className={styles.formGrid}><label>Estoque mínimo<input name="minimum" type="number" min="0" step="1" required /></label><label>Localização<input name="location" required placeholder="CD SP · A-01-01" /></label></div></>;
  else if (screen === "estoque") fields = <><label>Produto<select name="productId" required>{products.map((product) => <option value={product.id} key={product.id}>{product.name}</option>)}</select></label><div className={styles.formGrid}><label>Tipo<select name="type"><option value="IN">Entrada</option><option value="OUT">Saída</option><option value="TRANSFER">Transferência</option><option value="ADJUSTMENT">Ajuste positivo</option></select></label><label>Quantidade<input name="quantity" type="number" min="1" step="1" required /></label></div><label>Localização de destino<input name="location" required placeholder="CD SP · A-01-01" /></label><label>Motivo<input name="reason" required minLength={3} /></label></>;
  else if (screen === "equipe" && config) { const options: [string, string][] = role === "ADMIN" ? [["VISITOR", "Visitante"], ["CLIENT", "Cliente"]] : role === "DEVELOPER" ? [["VISITOR", "Visitante"], ["CLIENT", "Cliente"], ["ADMIN", "Administrador"], ["DEVELOPER", "Desenvolvedor"]] : [["VISITOR", "Visitante"], ["CLIENT", "Cliente"], ["ADMIN", "Administrador"], ["DEVELOPER", "Desenvolvedor"], ["OWNER", "Dono"]]; fields = <>{config.fields.map((field) => <label key={field.name}>{field.label}<input name={field.name} type={field.type ?? "text"} minLength={field.name === "password" ? 10 : 3} required /></label>)}<label>Cargo<select name="role" required>{options.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></>; }
  else fields = config?.fields.map((field) => <label key={field.name}>{field.label}{field.options ? <select name={field.name} required>{field.options.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select> : <input name={field.name} type={field.type ?? "text"} placeholder={field.placeholder} min={field.min} max={field.max} step={field.step} required />}</label>);
  const title = special ? (screen === "produtos" ? "Cadastrar produto" : "Movimentar estoque") : config?.title;
  const description = special ? (screen === "produtos" ? "Inclua os dados comerciais e de reposição." : "Toda movimentação ficará registrada na auditoria.") : config?.description;
  return <><button className={styles.primaryAction} onClick={() => { setMessage(""); setOpen(true); }}>{buttonLabel}</button>{open ? <div className={styles.overlay}><section className={styles.modal}><button className={styles.close} onClick={() => setOpen(false)}>×</button><h2>{title}</h2><p>{description}</p><form onSubmit={submit}>{fields}{message ? <output>{message}</output> : null}<button className={styles.submit} disabled={busy}>{busy ? "Salvando..." : "Salvar operação"}</button></form></section></div> : null}</>;
}
